name: main-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: github/checkout@v5
      - name: Setup App
        run: make setup
  tests:
    name: Test ğŸ§ª
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: make test
  check-lint:
    name: Check Eslint ğŸ“
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check Eslint
        run: make lint
