name: main-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup App
        run: make setup
        
      - name: Run Tests ğŸ§ª
        run: make test
        
      - name: Check Eslint ğŸ“
        run: make lint
