name: main-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Setup App
        run: make setup
        
      - name: Run Tests ğŸ§ª
        run: make test
        
      - name: Check Eslint ğŸ“
        run: make lint

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
